import React from 'react'
import { Link } from 'gatsby'
import Layout from '../components/layout'

const IndexPage = () => (
  <Layout>
    <h1>What is JAMstack?</h1>
    <p>Modern web development architecture based on client-side JavaScript, reusable APIs, and prebuilt Markup.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium reprehenderit facere labore, iste amet et eligendi vitae! Labore autem qui quia! Iusto aperiam repudiandae tempore soluta quam dolorum facilis consequuntur?
    Aut ab enim omnis dolor. Atque quam magnam repellendus amet vero non rem iusto illum delectus reprehenderit voluptatem, unde aspernatur, et consequatur enim quidem! Aperiam nostrum alias dolores ipsam quaerat.
    Tempore quisquam dolores aliquid facilis at consequuntur officia ipsam aperiam eos fugiat, hic enim ea laborum, porro sint iusto labore recusandae nulla natus expedita a exercitationem illo praesentium. Et, dolore.
    Ex quasi eius cumque, maxime accusamus reiciendis quibusdam ratione repellendus quia est, similique quisquam, alias excepturi dolorum laboriosam. Eos commodi impedit distinctio itaque repellat, consequuntur doloribus deleniti in saepe ab!
    Vero aut nisi temporibus fuga tenetur recusandae, quae dolore, quibusdam sapiente ea non eveniet ullam. Impedit ab voluptatum ratione provident dolorum nam excepturi fugit doloribus? Necessitatibus neque recusandae iusto. Vero?
    Exercitationem aut quasi esse praesentium incidunt officiis nemo ullam eum dolore neque nesciunt quibusdam minima doloribus sequi a suscipit voluptas deleniti quod, magnam at, aperiam quis nihil! Aperiam, dolor alias!
    Explicabo necessitatibus nobis, beatae quasi, nihil, architecto consequatur porro soluta laudantium accusamus dolorem doloribus! Non sed magni perspiciatis libero laborum officiis soluta corrupti architecto magnam, distinctio alias tenetur nihil sit?
    Delectus, consectetur dolorum totam iusto ipsa dignissimos maiores fugiat ipsum possimus neque. Aliquid animi neque a exercitationem? Exercitationem, itaque. Aut nulla est facere provident corrupti aliquid quam obcaecati nostrum eligendi?
    Tenetur nam fugiat odit, fuga alias velit aliquam natus nostrum officiis possimus aliquid ea incidunt, eligendi eum vero dolor fugit id repellendus, nihil molestiae quidem maiores a sunt. Obcaecati, eum.
    Sunt nesciunt veniam esse rerum saepe. Doloremque quis fugit accusantium. Aliquid quaerat, inventore tempore laudantium dignissimos itaque quasi deleniti fuga rerum nihil dicta aut corporis obcaecati, expedita officia labore quo.
    Debitis pariatur dolorum, a molestiae voluptate rem, quidem quam vel consectetur unde blanditiis repellat placeat inventore aliquid quasi veniam excepturi dolorem odio cum aspernatur iure architecto. Itaque eligendi at nesciunt.
    Pariatur, aliquid sequi! Voluptas fugiat dicta fugit, obcaecati accusamus quas at quod illo repudiandae maiores, numquam unde? Nam architecto, saepe, eveniet aspernatur natus enim facilis atque amet alias placeat perspiciatis!
    A adipisci suscipit alias repellendus, voluptatum assumenda maiores tenetur iusto! Commodi delectus, beatae sed error accusantium recusandae temporibus earum repellendus animi? Itaque ipsam commodi consequatur at perspiciatis ut amet illo!
    Autem laborum recusandae a exercitationem ab enim assumenda cumque nam totam temporibus, itaque obcaecati accusantium voluptates delectus inventore aspernatur ex non consectetur dicta impedit. Minima non reprehenderit quos aliquam vero!
    Ex, odit eveniet doloribus dolores, obcaecati consequuntur rerum blanditiis debitis aliquid ea recusandae! Ea omnis culpa laudantium temporibus in reiciendis autem adipisci quia eius natus ab, vitae illum consequatur ex.
    Optio earum omnis animi hic magni quas perferendis maxime deleniti impedit quia nam odio, vero est rerum dolores tenetur quidem voluptatum expedita eius. Consectetur nulla porro ipsum sint est tempore!
    Eaque, dolore corporis nam tempore dolor saepe recusandae eum pariatur ratione laboriosam vel illum molestias reprehenderit deserunt est quod. Id officiis dicta enim voluptas provident. Veritatis quasi doloremque quam in!
    Perspiciatis veritatis, voluptatibus eum officiis voluptates a ipsa ipsam natus consequatur placeat repudiandae temporibus non at recusandae alias facilis illum distinctio deleniti error veniam nulla eligendi fugit? Quasi, ipsa at.
    Dolore aspernatur deleniti sit eaque minima, nihil itaque, voluptatum corporis labore expedita facere at quidem autem. Nobis nam accusamus adipisci, vitae aliquid, placeat quod ut maiores eius, repudiandae dignissimos dolorum.
    Est quisquam quos magni aspernatur perspiciatis sint explicabo quas ipsam non iure natus minima obcaecati doloremque error magnam accusamus, enim, sapiente excepturi incidunt facere ipsum laboriosam dicta quidem! Molestias, omnis.
    Sunt, assumenda nihil? Similique minima quidem tempore sint temporibus architecto porro, sed ex impedit illo mollitia error ratione natus nihil soluta. Esse maiores quod blanditiis iusto minus illo vero rem?
    Animi vel, quibusdam nesciunt vitae distinctio deserunt voluptatum incidunt mollitia atque quos debitis veritatis totam consequatur beatae minima facere assumenda dignissimos nulla, error quod at, aliquid iusto. Veritatis, perspiciatis in.
    Fugit ipsum quis quidem accusantium asperiores et earum ullam rerum optio adipisci excepturi odit sapiente corrupti obcaecati dolorum, doloremque porro consequuntur quam illum corporis? Saepe dicta deserunt ullam tempore assumenda.
    Maxime ipsa magnam quos quisquam error esse. Autem, architecto? Praesentium libero odio repellendus similique, repudiandae atque vel deleniti placeat eos aut, velit quia perferendis, numquam mollitia illum consequatur excepturi unde!
    Aliquam enim temporibus nemo. Quis, placeat quae magni debitis blanditiis, alias fugiat corporis beatae neque facere consequatur totam error dicta quibusdam incidunt optio in atque provident nam omnis minima impedit.
    Minima excepturi tenetur esse blanditiis fugiat molestias quasi eveniet ab reiciendis magnam voluptate, quia fuga veritatis aut quisquam, eaque, officiis vero rem aliquam. Deserunt, optio amet debitis sint porro quia!
    Dolore itaque sapiente maiores aperiam, maxime molestiae recusandae ullam ipsum sunt mollitia, facere assumenda, eum placeat aut veniam sed in numquam! Tempore accusantium mollitia, officia eaque consectetur sapiente! Tenetur, voluptatibus!
    Tempore enim blanditiis reiciendis quis hic cupiditate, iusto corporis illum voluptate delectus dicta in accusantium perferendis dolore, ad repellat reprehenderit illo quam totam provident asperiores assumenda. Sequi eius id quasi?
    Fuga aliquid voluptatum pariatur quaerat eos modi aspernatur omnis dignissimos laborum? Animi, laudantium mollitia. Aperiam obcaecati praesentium voluptas voluptatum? Aperiam hic error amet, accusamus officia consequatur voluptas optio ducimus reiciendis.
    Assumenda accusantium veritatis animi rerum dolor rem quo optio nostrum iusto. Illum, deleniti distinctio eius earum similique sit doloribus numquam nemo repellat eveniet maxime blanditiis fugiat inventore expedita a. Ipsa?
    Quaerat nisi provident corporis facilis excepturi, ipsa voluptates. Sunt saepe iure aperiam. Doloribus ipsum porro a exercitationem molestias aliquam, asperiores eius? Voluptate, quisquam magnam? Natus perferendis est molestias dolore? Velit!
    Impedit velit reprehenderit ullam quisquam. Velit quidem corporis in ex quaerat sit laborum similique doloribus, adipisci fugiat illum odio perspiciatis voluptatibus expedita dolorum nemo voluptatum explicabo suscipit ullam ipsam dicta?
    Illum doloremque quibusdam dolor eius natus eum, exercitationem beatae suscipit corporis iste minima vero nobis maiores eos quo quidem ipsa explicabo debitis ipsum rem, quod obcaecati distinctio aliquam reprehenderit! Aliquam!
    Illum, quod nemo. Eligendi ipsum distinctio debitis fuga recusandae nam, repellendus veritatis facere, sint quas aspernatur! Magnam repellat excepturi optio fuga a reprehenderit quaerat alias ipsa sapiente assumenda. Magnam, velit!
    Soluta a blanditiis consequatur minus. Quibusdam nam assumenda commodi vero aliquid? Quidem tempore saepe exercitationem, eligendi quos fugit! Necessitatibus, debitis natus. Repellat distinctio deserunt voluptatem illo dolorem sed magni minus.
    Placeat hic dolorem quos. Repellendus dolores aliquam ut in eum beatae fugiat quia architecto praesentium reprehenderit soluta fuga illum laboriosam est distinctio ducimus tempora vel, optio nulla placeat? Beatae, itaque.
    Natus quae ratione molestiae. Atque laudantium distinctio ratione fugiat corporis alias amet aliquid asperiores veritatis iusto, provident deleniti illo unde tempora quia, non vel nulla soluta qui nisi, harum libero.
    Voluptas iste autem natus eligendi iusto. Dolorum voluptates omnis eos quos enim tempora ipsam repellat accusamus adipisci sapiente molestias dolor, iste deleniti, similique et delectus expedita non quaerat! Quas, commodi.
    Vel incidunt quos reiciendis unde quidem, nisi eius aspernatur pariatur doloribus illum quae repellendus ut aliquid eum voluptate dolore non consectetur quo qui amet dignissimos? Quos saepe numquam quas aut.
    Voluptas, et impedit. Laudantium culpa inventore similique possimus aperiam fuga beatae animi molestiae architecto non quo voluptatum nam hic, voluptate iste, vero laboriosam earum ratione porro labore? Alias, quasi enim.
    Nisi quibusdam, doloremque quae ut perspiciatis autem architecto doloribus corporis officiis repellat sed modi, non cupiditate vel? Iusto ea, eius sint obcaecati nesciunt ducimus aut, doloremque quam, neque tempore enim!
    Assumenda quod nulla distinctio esse modi, illo nesciunt unde, eaque non eius id, similique corrupti quos incidunt. Laborum asperiores culpa, ratione, sunt ut, veniam sit quis sed nulla iure commodi.
    Possimus, alias debitis consectetur maxime commodi corporis quibusdam, laborum expedita repellat amet quae vitae omnis ad optio nobis vel voluptas perspiciatis vero eos recusandae numquam officiis. Eius praesentium dolore consequuntur.
    Voluptatem quas eligendi iure itaque neque quis exercitationem recusandae vero iusto libero, at in, nesciunt maxime excepturi repudiandae possimus maiores inventore explicabo sed illo. Voluptatum saepe ea ullam consequuntur odit!
    Error, dolore! Aliquam, perferendis dignissimos provident nam laboriosam animi vitae soluta quia voluptas sunt tempore magni facilis at? Reprehenderit veniam sit eum nobis fugit perspiciatis tenetur quisquam cupiditate hic voluptatibus.
    Optio non tempora nobis voluptatum facere? Doloribus quas veritatis, ab fugiat, odit laborum ullam tenetur velit atque, officia omnis modi a impedit! Ea reiciendis soluta porro fugit aperiam, quasi atque.
    At velit esse in numquam eveniet iste eius. Laboriosam, quam sequi obcaecati aut natus officiis minus illo expedita fugit culpa ducimus distinctio architecto exercitationem dolorem nihil doloremque modi eligendi ea?
    Eos, itaque! Unde reiciendis soluta minus dolores nisi harum impedit dolor voluptatum, ipsum facilis omnis, maxime praesentium! Quasi quidem asperiores deserunt quod commodi dicta labore voluptate doloribus delectus, saepe odit.
    Quaerat numquam quis, porro pariatur ullam vel laudantium nesciunt fugit officiis asperiores sapiente! Sunt officia soluta, nulla similique eius vero veritatis quibusdam fugit eum placeat, exercitationem maiores quam perferendis magni?
    Asperiores quod, non nisi eos iste doloribus cum odit. Dolor, possimus excepturi porro repellat quasi, ratione voluptatem adipisci recusandae blanditiis hic accusamus quidem tempora deserunt distinctio magnam voluptas? Explicabo, obcaecati.
    Beatae eveniet assumenda repudiandae ullam dolores! Dicta, praesentium laboriosam amet minus aliquid, non earum repellendus aut culpa, sunt enim nam consequatur blanditiis natus dolore suscipit eveniet officiis harum velit maxime.
    Quisquam vero praesentium nihil quo sunt aperiam, ad totam et iste accusamus doloribus delectus veniam at, dignissimos omnis minima sequi commodi necessitatibus, reprehenderit dolores aliquid blanditiis vitae minus voluptate. Velit?
    Odio eligendi nemo et, sapiente, fugit sit, vero voluptatem sint adipisci ad doloremque expedita earum. Cumque quibusdam, fugiat dolor, obcaecati reprehenderit asperiores earum, possimus hic illum quae assumenda ipsa error.
    Cumque eveniet dolorum facere? Quisquam sit accusantium, nam voluptas at distinctio eos illo quo possimus autem perferendis. Et optio veritatis exercitationem, eum cum quae vel obcaecati, officia consectetur quo debitis!
    Rerum tenetur saepe repellendus nesciunt est? Distinctio reprehenderit veritatis ipsum eveniet ipsa beatae dolore velit corporis totam, porro magnam, doloremque, eligendi id. Sunt quia laudantium voluptate nihil architecto vero quis.
    Impedit voluptatum corrupti maiores fugit nemo ea, illum animi necessitatibus natus quod? Quidem sed suscipit ut iure. Sapiente nihil impedit fuga. Ipsa ratione quae nesciunt aut culpa nihil accusamus consectetur?
    Nostrum officiis explicabo quidem quaerat cum culpa aut, beatae assumenda iste fugit, quibusdam, facilis a blanditiis tempora dolorem voluptatem dicta id! Voluptatibus ipsum rerum provident voluptas. Ut laborum esse consequatur.
    Commodi, delectus vel sed nemo facere sequi a, eum assumenda ipsum ut perferendis. Nam alias dolorum amet consectetur? Incidunt debitis modi eos quas ab soluta quo perferendis iste. Minima, expedita?
    Magnam ea provident ullam sapiente, culpa eligendi deserunt perspiciatis? Commodi cumque adipisci recusandae deleniti aspernatur ex neque temporibus mollitia illum, pariatur id ea deserunt rem harum autem similique tempora labore!
    Impedit doloribus excepturi reiciendis sequi assumenda blanditiis beatae asperiores eum veniam ut id a temporibus, quam enim, at hic atque illum libero quasi ipsam dolorum suscipit dolorem deserunt. Libero, numquam.
    Alias magni omnis explicabo ad modi optio reiciendis qui, consequatur officiis sequi, necessitatibus corporis totam. Recusandae ea est blanditiis nobis doloribus similique nam harum eius saepe expedita. Tempora, nam cumque?
    Quae rem obcaecati quos deserunt iure veniam aperiam aliquid possimus fugiat voluptatem? Illum, perferendis alias animi doloremque molestias explicabo veniam. Dolores distinctio labore pariatur esse repellat! Modi inventore omnis laborum.
    Provident alias sed sequi odio exercitationem eligendi odit dolore aliquam! Repellendus, repudiandae similique voluptates eos quidem praesentium odit excepturi accusamus? Fugiat nihil unde aliquam aut asperiores? Maxime eum eos fugit.
    Praesentium omnis odit veniam dicta magni aliquam quia voluptates iusto ab, libero neque harum asperiores nostrum laudantium fuga explicabo in doloribus molestias aperiam tempora! Magni velit voluptate reprehenderit pariatur nostrum.
    Vitae corrupti molestias, placeat optio quae neque magnam iure, accusantium ipsa natus cupiditate architecto dolorem beatae, ad hic excepturi fugiat blanditiis nisi consectetur pariatur culpa quasi? Veritatis, vel! Quo, consequatur!
    Laudantium quo vitae expedita corporis sit eius est fugit necessitatibus harum soluta, nemo dignissimos nam eum impedit modi consectetur nobis quidem iusto! Quos inventore omnis quam ipsum, saepe pariatur iure!
    Totam iusto tempore suscipit reiciendis, nesciunt ex et maiores labore modi aperiam dolorem cum ipsam similique consequuntur vitae incidunt, doloribus fugit dicta ducimus commodi. Libero sequi deleniti porro quia! Ut.
    Eius ad suscipit eligendi, nobis laudantium dignissimos assumenda eaque maxime iusto doloremque sunt, ea odit voluptatibus minus, aspernatur voluptas et porro? Minus, voluptatem! Voluptatem iusto sequi quaerat. Minus, adipisci ex.
    Commodi, deleniti. Rerum quaerat corrupti voluptatum ut laudantium natus velit obcaecati nostrum labore. Maiores consequuntur perferendis blanditiis voluptatem mollitia tenetur velit quae molestiae vel, rerum nisi aperiam, quos culpa ducimus?
    Ab nulla deleniti quod accusantium alias illo veritatis iure, tenetur totam nemo iste obcaecati dicta, quam facilis est corrupti repellat. Quis libero facilis reprehenderit officiis accusantium voluptatum, totam animi ipsa?
    Provident ipsa veritatis est non itaque, doloremque dolore, dolorum consequatur error nam quaerat! Doloremque dicta amet reprehenderit ipsa iste beatae odio iure suscipit saepe, neque aliquid libero vel temporibus maiores.
    Repellendus, eligendi amet. Placeat provident numquam ex aut delectus temporibus sint eum neque atque quod magni ipsa repudiandae cumque id fuga magnam, veniam autem voluptates expedita. Inventore deleniti molestiae nam.
    Quam quo distinctio suscipit a autem nobis, accusantium perferendis inventore deserunt ducimus ad. Error temporibus sequi officia quasi obcaecati tempora, aut, quis quibusdam magni nobis, quo ipsam asperiores repellat fugit.
    Libero, assumenda? Provident, illum optio fugit pariatur vero quidem repellendus qui obcaecati, nulla totam laborum expedita, quam tempore! Atque ducimus et blanditiis aut odit quo quae vero a fugiat ex?
    Dolorum maiores, illo beatae molestias ab tempore modi quis excepturi! Distinctio quibusdam laborum unde eos, sequi dolore deserunt quod beatae sapiente quaerat officiis consequatur quasi nesciunt libero aliquid numquam illum.
    Consequatur neque vero deserunt dicta, doloremque ipsam veritatis perspiciatis cum autem doloribus omnis sit enim fuga ad sint error ut, qui ducimus, a reiciendis cumque! Assumenda commodi harum aut libero?
    Eaque aliquam quos numquam. Odit, neque? Harum aspernatur perferendis ullam delectus, placeat molestias aut natus architecto magnam est iusto modi aliquam vero nobis quod cupiditate rerum soluta ab maiores distinctio.
    Recusandae repudiandae optio natus quae atque labore iure amet architecto! Molestiae commodi ullam eaque inventore aspernatur temporibus, eius, rerum magnam numquam maxime ad neque amet nostrum praesentium dolorem! Non, architecto?
    Dolores magnam eveniet dolorum! Consequatur rem veritatis laboriosam error explicabo quia quidem ea aut assumenda culpa corporis veniam commodi temporibus sunt officia nesciunt soluta id, labore accusantium! Nobis, molestias nihil.
    Ad qui magnam aut necessitatibus tempora corrupti, nobis laboriosam assumenda quisquam perferendis quod voluptas quidem ipsum ea consequuntur officia ullam provident voluptatibus placeat, pariatur sed tempore maiores asperiores. Perspiciatis, similique.
    Vero repudiandae quibusdam facere? Necessitatibus maiores illum optio soluta. Obcaecati recusandae vero incidunt necessitatibus ipsa deleniti aliquam sint, assumenda, minus deserunt magnam magni rem, nihil quibusdam impedit ratione? Ullam, consectetur.
    Fugit quas ut fuga ea, ipsa ipsum! Quis perspiciatis deserunt ex laudantium. Cumque eligendi vero dignissimos, distinctio quisquam facere. Iusto non omnis nostrum sapiente eum dignissimos ratione tenetur a? At.
    Beatae quidem tempore, atque odit, in minus distinctio necessitatibus pariatur officia ullam sint. Labore, quidem totam? Amet quam quis quod aspernatur quasi labore quaerat, laborum blanditiis quos nihil aut optio!
    Nesciunt amet ratione odit exercitationem, ab facere mollitia itaque. Dolor asperiores, molestias at a harum blanditiis fugiat architecto minus voluptate corrupti id, veritatis delectus optio aliquam nostrum explicabo reprehenderit sed.
    Aliquid, modi repellendus. Provident eligendi ullam obcaecati ipsum debitis neque ea quaerat aperiam aliquam vero quae quasi suscipit dolores aut ipsam quidem nobis illo, voluptatibus nostrum nihil, laboriosam dolor modi.
    Tempora non vel repellat, enim quaerat fugiat dolor impedit magnam, illum doloribus consequatur voluptate reiciendis dolorum quam sapiente commodi ad itaque pariatur optio asperiores quae. Quod esse delectus nisi atque.
    Corrupti nemo provident, iure magni aliquid autem facilis vel iusto ab veritatis amet consectetur nisi! Exercitationem, esse corporis in earum quidem minima atque, unde necessitatibus qui accusamus fugiat pariatur aliquid?
    Eligendi sequi beatae tenetur molestias nulla incidunt maxime. Officiis, vitae cum doloremque, fuga atque magni unde asperiores molestias nobis rerum eum similique quia at quae dignissimos debitis! Assumenda, laudantium maxime.
    Beatae perferendis veniam accusantium fugiat dolorem. Mollitia atque explicabo dicta et sit voluptatibus quibusdam enim officia id, porro adipisci reiciendis aut eos cupiditate illum ex eaque harum blanditiis assumenda exercitationem.
    Perspiciatis reiciendis sint repellat, iusto, suscipit veritatis nihil atque culpa explicabo illo praesentium vel recusandae illum laboriosam, numquam ab nam rerum facilis fugit! Repudiandae, iusto. Mollitia, voluptatibus nulla. Quasi, culpa!
    Non, ad, in vitae alias at corporis sit blanditiis voluptatibus aut iste ratione dolorum, totam impedit ipsum modi dolorem quibusdam voluptates illo doloremque! Laboriosam, delectus! Neque eveniet ipsum qui minima.
    Ex eligendi praesentium, consequatur, odio sit minima reiciendis nostrum eveniet aperiam voluptate modi adipisci itaque labore asperiores earum. Dolore temporibus numquam accusamus illo ad perferendis libero ratione vitae? Eligendi, temporibus.
    Aliquid molestiae totam maiores alias explicabo ratione ea. Magni veniam eum quasi, ullam incidunt eveniet alias vero distinctio minima facilis doloremque quam numquam dolores, aliquam totam aperiam rem aliquid voluptatibus.
    Alias, distinctio ea veniam consequuntur quos, possimus id nostrum quo aliquam consequatur tempore deleniti ducimus omnis amet voluptas. Praesentium voluptates amet, doloribus impedit voluptatum voluptas placeat saepe tempora. Esse, cum.
    Doloremque porro ipsam natus saepe animi quas non delectus quia earum consequuntur. Facilis vel natus consequatur minus facere voluptatum officiis quam accusantium. Molestiae id laboriosam placeat ullam deleniti temporibus quas!
    Minima iste molestias facere aliquid autem? Aperiam dicta vel tenetur facilis perferendis facere numquam eum nisi, voluptates, ea porro eveniet sed? Soluta iste beatae omnis quasi voluptate dignissimos quod perferendis!
    Excepturi delectus quaerat minima, voluptatem sint beatae accusantium fuga tempora amet provident sit nulla ad esse. Quam ut nesciunt debitis velit totam sed cum facere laborum aliquam, veritatis maxime voluptate?
    Dicta pariatur commodi suscipit eum reiciendis inventore veritatis, ducimus doloremque tenetur, distinctio impedit. Non fuga ut quia architecto, inventore quod alias deserunt voluptatibus esse, distinctio asperiores voluptas corrupti laudantium doloribus?
    Fuga delectus, laudantium, nisi nulla error quod iusto quasi exercitationem, mollitia beatae modi dignissimos! Ipsa laboriosam quia alias magni consectetur, dolores, sed rem, ea facilis distinctio fugit illum et accusamus.
    Recusandae quasi quia beatae ratione possimus odio quidem atque voluptate ex, veniam eligendi vero voluptas, tempore rem quam consequuntur quos quisquam distinctio ad inventore vel obcaecati ducimus sapiente libero. Maiores.
    </p>
    <Link to="/page-2/">Reasons I Should Consider JAMstack</Link>
    
  </Layout>
)

export default IndexPage
